# Generated by Django 5.1.6 on 2025-02-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_community_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='slug',
        ),
    ]
