# Generated by Django 5.1.6 on 2025-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, default='nb', unique=True),
            preserve_default=False,
        ),
    ]
