# Generated by Django 5.1.6 on 2025-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_community_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='PostTitle', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
