# Generated by Django 5.1.6 on 2025-02-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.post'),
        ),
    ]
