# Generated by Django 5.1.6 on 2025-02-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_post_vote_count_vote_value_alter_vote_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
