# Generated by Django 5.1.6 on 2025-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
