# Generated by Django 5.1.6 on 2025-03-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_message_vote_count_messagevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=8000),
        ),
    ]
