# Generated by Django 5.1.6 on 2025-03-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
