# Generated by Django 5.1.6 on 2025-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_hiddenmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden_by_users_count',
            field=models.IntegerField(default=0),
        ),
    ]
