# Generated by Django 5.1.6 on 2025-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned')], default='active', max_length=10),
        ),
    ]
